# Site settings
title: Mike McWilliam
email: mjmcwilliam@outlook.com
#description: > # this means to ignore newlines until "baseurl:"
#  ...
#baseurl: "" # the subpath of your site, e.g. /blog
#baseurl: "/livingseas" # the subpath of your site, e.g. /blog
url: "https://mikemcwilliam.github.io" # the base hostname & protocol for your site
twitter_username: mikemcwilliam23
github_username:  mjmcwilliam

# Build settings
markdown: kramdown
#permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - pagemaster

paginate: 12
paginate_path: /page:num/

exclude: ['old_scripts',  'notes.txt']


collections:
  posts:
    output: TRUE
    source: gallery.csv
    id_key: name
    layout: post
  research:
   output: TRUE
